pipeline {
    agent { label '156_kangnam' }

    parameters {
        choice(name: 'ACTION', choices: ['restart', 'start', 'stop'], description: 'Hành động')
    } // đóng parameters

    environment {
        GIT_REPO = "https://github.com/thonguyenduc2010/odoo18.git"
        DB_NAME = "app_kn"
        TITLE = "API APP Loyalty KangNam"
        APP_URL = "https://loyalty.kangnam.com.vn"
        BRANCH_NAME = 'app_kn'
    } // đóng environment

    stages {

        stage('Check action') {
            steps {
                script {
                    env.ACTION = params.ACTION?.trim() ?: 'restart'
                    echo " ACTION selected:${env.ACTION}"
                }
            }
        } // đóng stage Check action

        stage('Checkout code') {
            steps {
                git(
                    branch: BRANCH_NAME,
                    credentialsId: env.Git_Credentials_Id,
                    url: "${GIT_REPO}"
                )
            }
        } // đóng stage Checkout code

        stage('Deploy') {
            steps {
                script {
                    if (env.ACTION == 'start') {
                        echo "🚀 First deployment"
                        sh """
                        mv docker-compose.yml.example docker-compose.yml
                        mv etc/odoo.conf.example etc/odoo.conf
                        mv etc/server.log.example etc/server.log

                        sudo mkdir -p data pg_data
                        sudo chown -R $USER entrypoint.sh data pg_data etc
                        sudo chmod -R 777 entrypoint.sh
                        sudo chmod -R 777 data pg_data etc/

                        docker-compose up -d
                        """
                    } else if ( env.ACTION == 'restart') {
                        echo "♻️ Restarting application"
                        sh "sudo chmod -R 777 data pg_data etc/"
                        sh "docker-compose restart"
                    } else {
                        echo "⛔ Stopping application..."
                        sh "docker-compose stop"
                    }
                }
            }
        } // đóng stage Deploy

    } // đóng stages

} // đóng pipeline

