pipeline {
    agent { label 'master' }

    parameters {
        choice(name: 'ACTION', choices: ['restart', 'start', 'stop'], description: 'Hành động')
    } // đóng parameters

    environment {
        TITLE = "Elasticsearch"
    } // đóng environment

    stages {

        stage('Check action') {
            steps {
                script {
                    env.ACTION = params.ACTION?.trim() ?: 'restart'
                    echo " ACTION selected:${env.ACTION}"
                }
            }
        } // đóng stage Check action

        stage('Checkout code') {
            steps {
                git(
                    branch: env.Branch_Name,
                    credentialsId: env.Git_Credentials_Id,
                    url: env.Git_Repo
                )
            }
        } // đóng stage Checkout code

        stage('Get Commit Info & Send to Telegram') {
            steps {
                script {
                    // Lấy thông tin từ Git
                    def commitHash = env.GIT_COMMIT ?: sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def commitMessage = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
                    def author = sh(script: "git log -1 --pretty=format:'%an'", returnStdout: true).trim()
                    def branch = env.GIT_BRANCH ?: sh(script: "git rev-parse --abbrev-ref HEAD", returnStdout: true).trim()
                    def repoUrl = env.GIT_URL ?: "Unknown Repo"

                    // Lấy danh sách và số lượng file thay đổi
                    def changedFiles = sh(script: "git diff-tree --no-commit-id --name-only -r ${commitHash}", returnStdout: true).trim()
                    def changedFilesCount = sh(script: "git diff-tree --no-commit-id --name-only -r ${commitHash} | wc -l", returnStdout: true).trim()

                    // Format danh sách file thay đổi
                    def fileList = changedFiles ? changedFiles.split("\n").collect { "🔹 " + it }.join("\n") : "Không có file thay đổi."

                    // Tạo nội dung tin nhắn Telegram
                    def message = """
                        🚀 *Commit mới trên: ${TITLE}*
                        🧑‍💻 *Author:* ${author}
                        📝 *Message:* ${commitMessage}
                        """.stripIndent()

                    sendTelegramMessage(message)
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    if (env.ACTION == 'start') {
                        echo "🚀 First deployment"
                        sh """
                        mv docker-compose.yml.example docker-compose.yml

                        sudo chown -R $USER elasticsearch kibana logstash
                        sudo chmod -R 777 elasticsearch/ kibana/ logstash/

                        docker-compose up -d
                        """
                    } else if ( env.ACTION == 'restart') {
                        echo "♻️ Restarting application"
                        sh "docker-compose restart"
                    } else {
                        echo "⛔ Stopping application..."
                        sh "docker-compose stop"
                    }
                }
            }
        } // đóng stage Deploy

    } // đóng stages

    post {
            success {
                script {
                    sendTelegramMessage("✅ Pipeline job ${TITLE} đã chạy thành công!")
                }
            }
            failure {
                script {
                    sendTelegramMessage("❌ Pipeline job ${TITLE} đã gặp lỗi! Kiểm tra log.")
                }
            }
        } // đóng post

} // đóng pipeline

def sendTelegramMessage(String message) {
    sh """
    curl -s -X POST "https://api.telegram.org/bot6102275063:${env.TELEGRAM_BOT_TOKEN}/sendMessage" \
    -d chat_id=${env.TELEGRAM_CHAT_ID} \
    -d text="${message}"
    """
} // đóng hàm sendTelegramMessage
