pipeline {
    agent { label '156_kangnam' }

    parameters {
        choice(name: 'ACTION', choices: ['start', 'restart', 'stop'], description: 'Hành động')
    } // đóng parameters

    environment {
        GIT_REPO = "https://github.com/thonguyenduc2010/odoo18.git"
        DB_NAME = "app_loyalty_kn"
    } // đóng environment

    stages {

        stage('Check action') {
            steps {
                script {
                    env.ACTION = params.ACTION?.trim() ?: 'restart'
                    echo " ACTION selected:${env.ACTION}"
                    echo " params selected:${params.ACTION}"
                }
            }
        } // đóng stage Check action

        stage('Checkout code') {
            steps {
                git(
                    branch: env.Branch_Name,
                    credentialsId: env.Git_Credentials_Id,
                    url: "${GIT_REPO}"
                )
            }
        } // đóng stage Checkout code

        stage('Deploy') {
            steps {
                script {
                    if (env.ACTION == 'start') {
                        echo "🚀 First deployment"
                        sh """ 
                        mv docker-compose.yml.example docker-compose.yml
                        mv etc/odoo.conf.example etc/odoo.conf

                        sudo mkdir -p data pg_data
                        sudo chown -R $USER entrypoint.sh data pg_data etc
                        sudo chmod -R 777 entrypoint.sh
                        sudo chmod -R 777 data pg_data etc

                        docker-compose up -d
                        """
                        sendTelegramMessage("🚀 App Loyalty Kangnam đã được triển khai thành công!")
                    } else if ( env.ACTION == 'restart') {
                        echo "♻️ Restarting application"
                        sh "docker-compose restart"
                        sendTelegramMessage("♻️ App Loyalty Kangnam đã được cập nhật và restart!")
                    } else if (env.ACTION == 'stop') {
                        echo "⛔ Stopping application..."
                        sh "docker-compose down"
                        sendTelegramMessage("⛔ App Loyalty Kangnam đã bị dừng!")
                    } else {
                        echo "⚠️ Lỗi: Hành động không hợp lệ!"
                    }
                }
            }
        } // đóng stage Deploy

        post {
            success {
                script {
                    sendTelegramMessage("✅ Pipeline job Loyalty Kangnam đã chạy thành công!")
                }
            } // đóng success
            failure {
                script {
                    sendTelegramMessage("❌ Pipeline job Loyalty Kangnam đã gặp lỗi! Kiểm tra log.")
                }
            } // đóng failure

        } // đóng post

    } // đóng stages

} // đóng pipeline

def sendTelegramMessage(String message) {
    sh """
    curl -s -X POST "https://api.telegram.org/bot6102275063:${env.TELEGRAM_BOT_TOKEN}/sendMessage" \
    -d chat_id=${env.TELEGRAM_CHAT_ID} \
    -d text="${message}"
    """
} // đóng hàm sendTelegramMessage
